<a href="https://colab.research.google.com/github/Ajmyquira/tweets-topic-modelling/blob/master/1-tweets-completition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tweets dataset completition

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

Reading all the tweets collected

In [ ]:
import pandas as pd
import glob
import os

# Merging the files
files_joined = os.path.join('/content/drive/MyDrive/UCSP/Data-Science-Topics/Data', "tweets0*.csv")

# Return a list of all joined files
list_files = glob.glob(files_joined)

print("** Merging multiple csv files into a single pandas dataframe **")
# Merge files by joining all files
tweets = pd.concat(map(pd.read_csv, list_files), ignore_index=True)
tweets

In [ ]:
tweets.shape

(2197456, 36)

There are 2 197 456 tweets collected.

In [ ]:
# Select the interest columns of 'date' and 'tweet'
tweets_filtered = pd.DataFrame(tweets[['date','tweet']])
tweets_filtered.columns = ['date','text']
tweets_filtered

In [ ]:
# Sorting the values by date
tweets_sorted = tweets_filtered.sort_values(by='date', ignore_index=True)
tweets_sorted

               date                                               text
0        2021-07-30  @PedroCastilloTe Hablas igual a Diosdado cabel...
1        2021-07-30  @Camilita_evans @PedroCastilloTe @AlanGarciaPe...
2        2021-07-30  Si ma침ana fueran las elecciones, volver칤a a vo...
3        2021-07-30  @PedroCastilloTe solo queda sacar a Bellido, s...
4        2021-07-30  @ebelinortiz @PedroCastilloTe @KeikoFujimori A...
...             ...                                                ...
2197451  2022-04-28  @oscardiazperu @PedroCastilloTe Un cojudo a la...
2197452  2022-04-28  @Frospigliosi No le va a pasar nada a @PedroCa...
2197453  2022-04-28  #CarlosBasombr칤o en Canal N, critica al JNE po...
2197454  2022-04-28  #28Abr 游깵 | Pedro Castillo present칩 propuesta p...
2197455  2022-04-28  @PTV_Noticias El "ni침ito" @ilichlopez2022 como...

[2197456 rows x 2 columns]

In this part, the tweets of some missing days are completed with the tweets of nearby days.

In [ ]:
# Current day with tweets
cur_day = ['2021-07-30',
           '2021-07-30',
           '2021-09-24',
           '2021-10-11',
           '2021-11-06',
           '2021-12-14',
           '2022-01-17',
           '2022-01-31',
           '2022-02-16',
           '2022-02-24',
           '2022-03-13',
           '2022-03-29',
           '2022-03-29',
           '2022-04-03',
           '2022-04-03',
           '2022-04-27',
           '2022-04-27']

# New day without tweets
new_day = ['2021-07-28',
           '2021-07-29',
           '2021-09-25',
           '2021-10-10',
           '2021-11-07',
           '2021-12-13',
           '2022-01-16',
           '2022-01-30',
           '2022-02-15',
           '2022-02-23',
           '2022-03-12',
           '2022-03-30',
           '2022-03-31',
           '2022-04-01',
           '2022-04-02',
           '2022-04-29',
           '2022-04-30']

# Select and duplicate the tweets for the current date
tweets_by_day = tweets_sorted[tweets_sorted['date'] == cur_day[0]]
print(tweets_by_day.shape)
# Change the date for the duplicate selection
n_tweets_by_day = tweets_by_day.replace({cur_day[0]: new_day[0]})
# Adding the new tweets
new_tweets = pd.concat([tweets_sorted, n_tweets_by_day])
new_tweets.index = range(new_tweets.shape[0])
n_tweets_sorted = new_tweets.sort_values(by='date', ignore_index=True)

for i in range(1, len(new_day)):
  # Select and duplicate the tweets for the current date
  tweets_by_day = tweets_sorted[tweets_sorted['date'] == cur_day[i]]
  print(tweets_by_day.shape)
  # Change the date for the duplicate selection
  n_tweets_by_day = tweets_by_day.replace({cur_day[i]: new_day[i]})
  # Adding the new tweets
  new_tweets = pd.concat([new_tweets, n_tweets_by_day])
  new_tweets.index = range(new_tweets.shape[0])
  n_tweets_sorted = new_tweets.sort_values(by='date', ignore_index=True)

n_tweets_sorted

(21513, 2)
(21513, 2)
(2484, 2)
(397, 2)
(4237, 2)
(2666, 2)
(2722, 2)
(2930, 2)
(4070, 2)
(1022, 2)
(875, 2)
(11820, 2)
(11820, 2)
(6857, 2)
(6857, 2)
(8022, 2)
(8022, 2)

               date                                               text
0        2021-07-28  @PedroCastilloTe Hablas igual a Diosdado cabel...
1        2021-07-28  @ebelinortiz @PedroCastilloTe @KeikoFujimori Y...
2        2021-07-28  #Per칯 #M칠xico Pedro Castillo desaf칤a a Per칰 co...
3        2021-07-28  @Perulibreprensa NOS MENTISTE @PedroCastilloTe...
4        2021-07-28  Parece que a alguien le gust칩 escuchar que "ha...
...             ...                                                ...
2315278  2022-04-30  @RichardArcePeru @PedroCastilloTe Es un gobier...
2315279  2022-04-30  @JorgeMunozPe @JNE_Peru Ahora ser칤a bueno que ...
2315280  2022-04-30  @NoDignos @PedroCastilloTe @congresoperu Jsjsjsjs
2315281  2022-04-30  Now playing Pedro Castillo aosto 13,2021 by Pe...
2315282  2022-04-30  @radio_santarosa @rmapalacios @PedroCastilloTe...

[2315283 rows x 2 columns]

In [ ]:
# Tranforming the date values type to datetime
n_tweets_date = n_tweets_sorted.copy()
n_tweets_date['date'] = pd.to_datetime(n_tweets_date['date'])

In [ ]:
# Grouping the dates by days
n_tweets_date["my_day"] = n_tweets_date.date.dt.date

In [ ]:
# Checking the amount of tweets per day
for day, datos in n_tweets_date.groupby("my_day"):
  print("{}: {}".format(day, len(datos)))

2021-07-28: 21513
2021-07-29: 21513
2021-07-30: 21513
2021-07-31: 13787
2021-08-01: 14659
2021-08-02: 11214
2021-08-03: 9933
2021-08-04: 10011
2021-08-05: 10072
2021-08-06: 9739
2021-08-07: 6383
2021-08-08: 6205
2021-08-09: 7155
2021-08-10: 6993
2021-08-11: 8345
2021-08-12: 9047
2021-08-13: 6166
2021-08-14: 5855
2021-08-15: 9431
2021-08-16: 5954
2021-08-17: 7491
2021-08-18: 11441
2021-08-19: 7048
2021-08-20: 11033
2021-08-21: 6610
2021-08-22: 5249
2021-08-23: 6349
2021-08-24: 6035
2021-08-25: 11281
2021-08-26: 4902
2021-08-27: 6162
2021-08-28: 4414
2021-08-29: 2296
2021-08-30: 2820
2021-08-31: 10676
2021-09-01: 6707
2021-09-02: 8932
2021-09-03: 7355
2021-09-04: 6170
2021-09-05: 4202
2021-09-06: 7130
2021-09-07: 5218
2021-09-08: 3409
2021-09-09: 4819
2021-09-10: 6028
2021-09-11: 10859
2021-09-12: 4171
2021-09-13: 5048
2021-09-14: 4170
2021-09-15: 4800
2021-09-16: 4439
2021-09-17: 7495
2021-09-18: 10109
2021-09-19: 9359
2021-09-20: 11032
2021-09-21: 10414
2021-09-22: 6594
2021-09-23: 3789
2021-09-24: 2484
2021-09-25: 2484
2021-09-26: 11059
2021-09-27: 8387
2021-09-28: 3099
2021-09-29: 2464
2021-09-30: 12192
2021-10-01: 7233
2021-10-02: 4786
2021-10-03: 10968
2021-10-04: 7124
2021-10-05: 8664
2021-10-06: 18152
2021-10-07: 13297
2021-10-08: 6205
2021-10-09: 3578
2021-10-10: 397
2021-10-11: 397
2021-10-12: 4589
2021-10-13: 3768
2021-10-14: 6997
2021-10-15: 7126
2021-10-16: 3658
2021-10-17: 4377
2021-10-18: 10949
2021-10-19: 11338
2021-10-20: 6026
2021-10-21: 4116
2021-10-22: 3679
2021-10-23: 3488
2021-10-24: 3927
2021-10-25: 7274
2021-10-26: 8919
2021-10-27: 9862
2021-10-28: 6738
2021-10-29: 4383
2021-10-30: 936
2021-10-31: 4706
2021-11-01: 7741
2021-11-02: 14579
2021-11-03: 9640
2021-11-04: 11264
2021-11-05: 7460
2021-11-06: 4237
2021-11-07: 4237
2021-11-08: 7312
2021-11-09: 13481
2021-11-10: 22168
2021-11-11: 10868
2021-11-12: 5223
2021-11-13: 4272
2021-11-14: 9765
2021-11-15: 5939
2021-11-16: 3644
2021-11-17: 3645
2021-11-18: 12717
2021-11-19: 8607
2021-11-20: 6987
2021-11-21: 4783
2021-11-22: 8802
2021-11-23: 9785
2021-11-24: 11630
2021-11-25: 9486
2021-11-26: 8682
2021-11-27: 6343
2021-11-28: 10477
2021-11-29: 10595
2021-11-30: 16503
2021-12-01: 11127
2021-12-02: 11124
2021-12-03: 9846
2021-12-04: 7978
2021-12-05: 8246
2021-12-06: 6698
2021-12-07: 14158
2021-12-08: 11063
2021-12-09: 6017
2021-12-10: 4896
2021-12-11: 5190
2021-12-12: 3476
2021-12-13: 2666
2021-12-14: 2666
2021-12-15: 6240
2021-12-16: 8449
2021-12-17: 5093
2021-12-18: 3900
2021-12-19: 7532
2021-12-20: 9528
2021-12-21: 13217
2021-12-22: 7734
2021-12-23: 8238
2021-12-24: 6837
2021-12-25: 3033
2021-12-26: 3858
2021-12-27: 8442
2021-12-28: 10826
2021-12-29: 8036
2021-12-30: 1279
2021-12-31: 5625
2022-01-01: 2981
2022-01-02: 3427
2022-01-03: 3677
2022-01-04: 4680
2022-01-05: 6684
2022-01-06: 5129
2022-01-07: 8458
2022-01-08: 4772
2022-01-09: 4383
2022-01-10: 3380
2022-01-11: 3147
2022-01-12: 4250
2022-01-13: 5275
2022-01-14: 6115
2022-01-15: 4392
2022-01-16: 2722
2022-01-17: 2722
2022-01-18: 6606
2022-01-19: 9806
2022-01-20: 8237
2022-01-21: 13015
2022-01-22: 4950
2022-01-23: 12591
2022-01-24: 18747
2022-01-25: 24809
2022-01-26: 19888
2022-01-27: 16488
2022-01-28: 14349
2022-01-29: 11738
2022-01-30: 2930
2022-01-31: 2930
2022-02-01: 26629
2022-02-02: 15895
2022-02-03: 15122
2022-02-04: 21660
2022-02-05: 12166
2022-02-06: 8888
2022-02-07: 14904
2022-02-08: 20443
2022-02-09: 13751
2022-02-10: 9536
2022-02-11: 11238
2022-02-12: 5960
2022-02-13: 5450
2022-02-14: 6952
2022-02-15: 4070
2022-02-16: 4070
2022-02-17: 9741
2022-02-18: 6859
2022-02-19: 4754
2022-02-20: 4258
2022-02-21: 5803
2022-02-22: 3833
2022-02-23: 1022
2022-02-24: 1022
2022-02-25: 18473
2022-02-26: 35403
2022-02-27: 26014
2022-02-28: 17335
2022-03-01: 11761
2022-03-02: 8557
2022-03-03: 4253
2022-03-04: 5993
2022-03-05: 6904
2022-03-06: 5520
2022-03-07: 5854
2022-03-08: 10746
2022-03-09: 7565
2022-03-10: 8081
2022-03-11: 7205
2022-03-12: 875
2022-03-13: 875
2022-03-14: 11704
2022-03-15: 19587
2022-03-16: 9777
2022-03-17: 17217
2022-03-18: 7511
2022-03-19: 5312
2022-03-20: 5431
2022-03-21: 5327
2022-03-22: 4273
2022-03-23: 5509
2022-03-24: 5334
2022-03-25: 7278
2022-03-26: 5185
2022-03-27: 6777
2022-03-28: 17846
2022-03-29: 11820
2022-03-30: 11820
2022-03-31: 11820
2022-04-01: 6857
2022-04-02: 6857
2022-04-03: 6857
2022-04-04: 26251
2022-04-05: 57285
2022-04-06: 22333
2022-04-07: 16133
2022-04-08: 9652
2022-04-09: 5620
2022-04-10: 5517
2022-04-11: 6746
2022-04-12: 5010
2022-04-13: 5414
2022-04-14: 6299
2022-04-15: 5118
2022-04-16: 4128
2022-04-17: 3089
2022-04-18: 5516
2022-04-19: 7187
2022-04-20: 4606
2022-04-21: 4309
2022-04-22: 9163
2022-04-23: 7168
2022-04-24: 5472
2022-04-25: 6465
2022-04-26: 5129
2022-04-27: 8022
2022-04-28: 3530
2022-04-29: 8022
2022-04-30: 8022

In [ ]:
n_tweets_sorted

               date                                               text
0        2021-07-28  @PedroCastilloTe Hablas igual a Diosdado cabel...
1        2021-07-28  @ebelinortiz @PedroCastilloTe @KeikoFujimori Y...
2        2021-07-28  #Per칯 #M칠xico Pedro Castillo desaf칤a a Per칰 co...
3        2021-07-28  @Perulibreprensa NOS MENTISTE @PedroCastilloTe...
4        2021-07-28  Parece que a alguien le gust칩 escuchar que "ha...
...             ...                                                ...
2315278  2022-04-30  @RichardArcePeru @PedroCastilloTe Es un gobier...
2315279  2022-04-30  @JorgeMunozPe @JNE_Peru Ahora ser칤a bueno que ...
2315280  2022-04-30  @NoDignos @PedroCastilloTe @congresoperu Jsjsjsjs
2315281  2022-04-30  Now playing Pedro Castillo aosto 13,2021 by Pe...
2315282  2022-04-30  @radio_santarosa @rmapalacios @PedroCastilloTe...

[2315283 rows x 2 columns]

In [ ]:
# Saving the new tweets data completed
n_tweets_sorted.to_json("/content/drive/MyDrive/UCSP/Data-Science-Topics/Data/all_tweets.json", index=False, orient="split")